### ISSUE TITLE
Music -- moved to kittyMusic.library - case closed.

### ISSUE THREAD

**Issue by khval** [khval/AmosKittens#31]

**Comment by khval** [comment]
Mvolume,  , ,Track Stop, Track loop on, Track loop of, Track play, Track Load, Med load, Med play, Med Stop, Med Count, Med Mini On

**Comment by SamuraiCrow** [comment]
[LibXMP](https://sourceforge.net/projects/xmp/files/libxmp/4.4.1/) will play most module file formats including Amos muxic banks.

**Comment by khval** [comment]
I have looked at some places it says MIT some places it says GPL, GPL and MIT are not compatible licenses. That sucks when you package things.

**Comment by SamuraiCrow** [comment]
The library is MIT but the player that calls it is GPL, I think.

**Comment by khval** [comment]
This issue belongs to music extension now, I try find a way to move it.
